Update 49vmapper

diff --git a/scrips/49vmapper b/scrips/49vmapper
--- a/scrips/49vmapper
+++ b/scrips/49vmapper
@@ -257,14 +257,14 @@ if [ -f $initdir/init_done ]; then
       echo "`date +%Y-%m-%d_%T` 49vmapper: Installed PoGo"  >> $logfile
 
       if [ -f /sdcard/useVMCdevelop ] ;then
-        until /system/bin/curl -s -k -L --fail --show-error -o /system/bin/ATVdetailsSender.sh https://raw.githubusercontent.com/v-mapper/vmconf/develop/ATVdetailsSender.sh || { echo "`date +%Y-%m-%d_%T` 49vmapper: Download ATVdetailsSender.sh failed for origin=$origin, auth=$auth, server=$server from ip=$ip. Exit script" >> $logfile ; exit 1; } ;do
+        until /system/bin/curl -s -k -L --fail --show-error -o /system/bin/ATVdetailsSender.sh https://raw.githubusercontent.com/v-mapper/vmconf/develop9/scrips/ATVdetailsSender.sh || { echo "`date +%Y-%m-%d_%T` 49vmapper: Download ATVdetailsSender.sh failed for origin=$origin, auth=$auth, server=$server from ip=$ip. Exit script" >> $logfile ; exit 1; } ;do
           sleep 2
         done
         chmod +x /system/bin/ATVdetailsSender.sh
         log_msg 2 "ATVdetailsSender.sh downloaded"
         echo "`date +%Y-%m-%d_%T` 49vmapper: Installed ATVdetailsSender.sh, from vmconf develop !!"  >> $logfile
       else
-        until /system/bin/curl -s -k -L --fail --show-error -o /system/bin/ATVdetailsSender.sh https://raw.githubusercontent.com/ReuschelCGN/aconf/vconf/scrips/ATVdetailsSender.sh || { echo "`date +%Y-%m-%d_%T` 49vmapper: Download ATVdetailsSender.sh failed for origin=$origin, auth=$auth, server=$server from ip=$ip. Exit script" >> $logfile ; exit 1; } ;do
+        until /system/bin/curl -s -k -L --fail --show-error -o /system/bin/ATVdetailsSender.sh https://raw.githubusercontent.com/v-mapper/vmconf/main9/scrips/ATVdetailsSender.sh || { echo "`date +%Y-%m-%d_%T` 49vmapper: Download ATVdetailsSender.sh failed for origin=$origin, auth=$auth, server=$server from ip=$ip. Exit script" >> $logfile ; exit 1; } ;do
           sleep 2
         done
         chmod +x /system/bin/ATVdetailsSender.sh
